// packages/vue/src/FadeGroup.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { stagger, type FadeProps, type MotionIntent, type TimingScale, type TimingAlias } from '@fade-animation/core';
import Fade from './Fade.vue';

const props = withDefaults(
  defineProps<{
    in?: boolean;
    duration?: number;
    easing?: string;
    preset?: FadeProps['preset'];
    timing?: TimingScale | TimingAlias;
    intent?: MotionIntent;
    staggerInterval: number;
    staggerBaseDelay?: number;
    staggerDirection?: 'forward' | 'reverse' | 'center';
    onAnimationEnd?: () => void;
    className?: string;
  }>(),
  { in: true, staggerBaseDelay: 0, staggerDirection: 'forward' }
);

const slots = defineSlots<{ default(): VNode[] }>();

const childCount = computed(() => {
  const children = slots.default?.();
  return children ? children.length : 0;
});

const delays = computed(() => {
  return stagger(childCount.value, {
    interval: props.staggerInterval,
    baseDelay: props.staggerBaseDelay,
    direction: props.staggerDirection,
  });
});
</script>

<template>
  <template v-for="(child, index) in slots.default?.()" :key="index">
    <Fade
      :in="props.in" :duration="props.duration" :easing="props.easing"
      :preset="props.preset" :timing="props.timing" :intent="props.intent"
      :delay="delays[index]"
      :onAnimationEnd="index === (childCount - 1) ? props.onAnimationEnd : undefined"
      :className="props.className"
    >
      <component :is="child" />
    </Fade>
  </template>
</template>

// packages/react/src/FadeGroup.tsx
import React, { type ReactNode, Children } from 'react';
import { stagger, type StaggerOptions, type FadeProps } from '@fade-animation/core';
import { Fade } from './Fade';

export interface FadeGroupProps extends Omit<FadeProps, 'delay'> {
  /** 编排配置 */
  stagger: StaggerOptions;
  children?: ReactNode;
}

/**
 * 编排组件：为多个子元素自动计算交错延迟，实现有节奏的淡入/淡出效果。
 *
 * @example
 * <FadeGroup in={true} intent="enter" stagger={{ interval: 50 }}>
 *   <Card>1</Card>
 *   <Card>2</Card>
 *   <Card>3</Card>
 * </FadeGroup>
 */
export const FadeGroup: React.FC<FadeGroupProps> = ({
  stagger: staggerOpts,
  children,
  ...fadeProps
}) => {
  const childArray = Children.toArray(children);
  const delays = stagger(childArray.length, staggerOpts);

  return (
    <>
      {childArray.map((child, index) => (
        <Fade key={index} {...fadeProps} delay={delays[index]}>
          {child}
        </Fade>
      ))}
    </>
  );
};
