// packages/vue/src/Motion.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue';
import {
  resolveConfig,
  resolveEffectStyles,
  EFFECT_PRESETS,
  type FadeProps,
  type MotionEffect,
  type EffectPresetName,
  type MotionIntent,
  type TimingScale,
  type TimingAlias,
} from '@fade-animation/core';

const props = withDefaults(
  defineProps<{
    in?: boolean;
    effect?: MotionEffect[] | EffectPresetName;
    duration?: number;
    delay?: number;
    easing?: string;
    preset?: FadeProps['preset'];
    timing?: TimingScale | TimingAlias;
    intent?: MotionIntent;
    onAnimationEnd?: () => void;
    className?: string;
  }>(),
  {
    in: true,
    effect: () => [{ type: 'fade' }] as MotionEffect[],
  }
);

function getEffects(): MotionEffect[] {
  return typeof props.effect === 'string'
    ? [...EFFECT_PRESETS[props.effect as EffectPresetName]]
    : (props.effect as MotionEffect[]);
}

function getResolvedConfig() {
  return resolveConfig({
    duration: props.duration,
    delay: props.delay,
    easing: props.easing,
    preset: props.preset,
    timing: props.timing,
    intent: props.intent,
  });
}

// --- Collapse detection ---
const effects = computed(() => getEffects());
const collapseEffect = computed(() =>
  effects.value.find(e => e.type === 'collapse') as
    | (MotionEffect & { type: 'collapse'; collapsedHeight?: number })
    | undefined
);
const hasCollapse = computed(() => collapseEffect.value !== undefined);
const collapsedHeight = computed(() => collapseEffect.value?.collapsedHeight ?? 0);

// --- First render tracking (Req 20.5) ---
// Before onMounted fires, isFirstRender is true → skip initial animation
let isFirstRender = true;

// Track whether we're in expanded state (max-height is "none")
let isExpanded = props.in && hasCollapse.value;

// Content height measured via scrollHeight (Req 11.1)
const contentHeight = ref(0);

// Compute effect styles, passing contentHeight for Collapse
const effectStyles = computed(() =>
  resolveEffectStyles(effects.value, props.in, hasCollapse.value ? contentHeight.value : undefined)
);

// --- Initial styles ---
// For Collapse on first render: set static state without animation (Req 20.1, 20.2)
const currentStyles = ref<Record<string, string>>((() => {
  if (hasCollapse.value && isFirstRender) {
    const baseStyles = props.in ? effectStyles.value.to : effectStyles.value.from;
    if (props.in) {
      return { ...baseStyles, 'max-height': 'none' };
    } else {
      return { ...baseStyles, 'max-height': collapsedHeight.value + 'px' };
    }
  }
  return props.in ? effectStyles.value.from : effectStyles.value.to;
})());

const rootRef = ref<HTMLDivElement | null>(null);
let callbackFired = false;
let safetyTimer: ReturnType<typeof setTimeout> | null = null;
let transitionEndHandler: ((e: TransitionEvent) => void) | null = null;
let resizeObserver: ResizeObserver | null = null;
let rafId: number | null = null;

function cleanup() {
  if (safetyTimer !== null) {
    clearTimeout(safetyTimer);
    safetyTimer = null;
  }
  if (rafId !== null) {
    cancelAnimationFrame(rafId);
    rafId = null;
  }
  const el = rootRef.value;
  if (el && transitionEndHandler) {
    el.removeEventListener('transitionend', transitionEndHandler);
    transitionEndHandler = null;
  }
}

function cleanupResizeObserver() {
  if (resizeObserver) {
    resizeObserver.disconnect();
    resizeObserver = null;
  }
}

// Handle expand/collapse animation completion for Collapse effect
function handleCollapseTransitionEnd(entering: boolean) {
  if (!hasCollapse.value || !rootRef.value) return;
  if (entering) {
    // Expand animation completed: set max-height to "none" (Req 11.3)
    isExpanded = true;
    currentStyles.value = { ...currentStyles.value, 'max-height': 'none' };
  } else {
    isExpanded = false;
  }
}

// --- onMounted: mark first render done, set up ResizeObserver (Req 11.5, 20.5) ---
onMounted(() => {
  const el = rootRef.value;

  // Measure content height on mount (Req 11.1)
  if (hasCollapse.value && el) {
    contentHeight.value = el.scrollHeight;

    // Set up ResizeObserver to track content size changes (Req 11.5, 11.6)
    resizeObserver = new ResizeObserver(() => {
      if (el) {
        contentHeight.value = el.scrollHeight;
      }
    });
    resizeObserver.observe(el);
  }

  // Mark first render complete (Req 20.5)
  isFirstRender = false;
});

// --- Main animation watcher ---
watch(
  () => props.in,
  (entering) => {
    cleanup();
    callbackFired = false;

    const resolved = getResolvedConfig();
    const effs = getEffects();
    const resolvedHasCollapse = effs.some(e => e.type === 'collapse');
    const resolvedCollapseEffect = effs.find(e => e.type === 'collapse') as
      | (MotionEffect & { type: 'collapse'; collapsedHeight?: number })
      | undefined;
    const resolvedCollapsedHeight = resolvedCollapseEffect?.collapsedHeight ?? 0;

    const styles = resolveEffectStyles(
      effs,
      entering,
      resolvedHasCollapse ? contentHeight.value : undefined,
    );
    const target = entering ? styles.to : styles.from;

    // Skip animation on first render for Collapse (Req 20.5)
    if (isFirstRender) {
      if (resolvedHasCollapse) {
        if (entering) {
          isExpanded = true;
          currentStyles.value = { ...styles.to, 'max-height': 'none' };
        } else {
          isExpanded = false;
          currentStyles.value = { ...styles.from, 'max-height': resolvedCollapsedHeight + 'px' };
        }
        if (props.onAnimationEnd) {
          props.onAnimationEnd();
        }
        return;
      }
    }

    // Reduced motion: skip animation
    if (resolved.reducedMotion && resolved.duration === 0) {
      if (resolvedHasCollapse) {
        if (entering) {
          currentStyles.value = { ...target, 'max-height': 'none' };
          isExpanded = true;
        } else {
          currentStyles.value = { ...target, 'max-height': resolvedCollapsedHeight + 'px' };
          isExpanded = false;
        }
      } else {
        currentStyles.value = target;
      }
      if (props.onAnimationEnd && !callbackFired) {
        callbackFired = true;
        props.onAnimationEnd();
      }
      return;
    }

    // For Collapse: handle the "none" → scrollHeight snap before collapsing (Req 11.4)
    if (resolvedHasCollapse && !entering && isExpanded) {
      const el = rootRef.value;
      const currentScrollHeight = el ? el.scrollHeight : contentHeight.value;
      const snapStyles = { ...styles.to, 'max-height': currentScrollHeight + 'px', overflow: 'hidden' };
      currentStyles.value = snapStyles;
      isExpanded = false;

      // Use rAF to ensure the snap is painted, then transition to collapsedHeight
      rafId = requestAnimationFrame(() => {
        currentStyles.value = { ...target };
      });

      const fireCallback = () => {
        if (props.onAnimationEnd && !callbackFired) {
          callbackFired = true;
          handleCollapseTransitionEnd(entering);
          props.onAnimationEnd();
        }
      };

      const el2 = rootRef.value;
      transitionEndHandler = (e: TransitionEvent) => {
        if (styles.transitionProperties.includes(e.propertyName)) {
          fireCallback();
        }
      };
      if (el2) {
        el2.addEventListener('transitionend', transitionEndHandler);
      }

      safetyTimer = setTimeout(() => {
        fireCallback();
      }, resolved.duration + resolved.delay + 50);

      return;
    }

    // Standard animation path (also handles Collapse expand)
    currentStyles.value = entering ? styles.from : styles.to;

    const fireCallback = () => {
      if (props.onAnimationEnd && !callbackFired) {
        callbackFired = true;
        if (resolvedHasCollapse) {
          handleCollapseTransitionEnd(entering);
        }
        props.onAnimationEnd();
      }
    };

    nextTick(() => {
      rafId = requestAnimationFrame(() => {
        currentStyles.value = target;
      });
    });

    const el = rootRef.value;
    transitionEndHandler = (e: TransitionEvent) => {
      if (styles.transitionProperties.includes(e.propertyName)) {
        fireCallback();
      }
    };
    if (el) {
      el.addEventListener('transitionend', transitionEndHandler);
    }

    safetyTimer = setTimeout(() => {
      fireCallback();
    }, resolved.duration + resolved.delay + 50);
  },
  { immediate: true }
);

// Re-setup ResizeObserver when hasCollapse changes
watch(hasCollapse, (newVal) => {
  cleanupResizeObserver();
  if (newVal) {
    const el = rootRef.value;
    if (el) {
      contentHeight.value = el.scrollHeight;
      resizeObserver = new ResizeObserver(() => {
        if (el) {
          contentHeight.value = el.scrollHeight;
        }
      });
      resizeObserver.observe(el);
    }
  }
});

onUnmounted(() => {
  cleanup();
  cleanupResizeObserver();
});

const inlineStyle = computed(() => {
  const config = getResolvedConfig();
  const styles = effectStyles.value;

  let transitionValue: string;
  // First render with collapse: no transition
  if (hasCollapse.value && isFirstRender) {
    transitionValue = 'none';
  } else if (config.reducedMotion && config.duration === 0) {
    transitionValue = 'none';
  } else {
    transitionValue = styles.transitionProperties
      .map((prop: string) => `${prop} ${config.duration}ms ${config.easing} ${config.delay}ms`)
      .join(', ');
  }

  return {
    ...currentStyles.value,
    transition: transitionValue,
  };
});
</script>

<template>
  <div ref="rootRef" :class="props.className" :style="inlineStyle">
    <slot />
  </div>
</template>

// packages/react/src/Motion.tsx
import React, { useEffect, useCallback, useRef, useState, type ReactNode, type CSSProperties } from 'react';
import {
  resolveConfig,
  resolveEffectStyles,
  type FadeProps,
  type MotionEffect,
  type EffectPresetName,
  EFFECT_PRESETS,
} from '@fade-animation/core';

const DEFAULT_EFFECT: MotionEffect[] = [{ type: 'fade' }];

export interface MotionProps extends Omit<FadeProps, 'in'> {
  /** 控制动画方向：true 为进入，false 为退出 */
  in?: boolean;
  /** 效果数组或预设名称 */
  effect?: MotionEffect[] | EffectPresetName;
  children?: ReactNode;
}

/**
 * 通用 Motion 组件。
 *
 * 支持 fade、scale、slide、flip、collapse 及其组合效果。
 * <Fade> 是它的特化版本（effect 固定为 fade）。
 *
 * @example
 * <Motion in={show} effect="scale-fade-in" intent="enter">
 *   <Card />
 * </Motion>
 *
 * <Motion in={show} effect={[{ type: 'fade' }, { type: 'slide', direction: 'up' }]}>
 *   <Panel />
 * </Motion>
 *
 * <Motion in={expanded} effect={[{ type: 'collapse' }]}>
 *   <CollapsibleContent />
 * </Motion>
 */
export const Motion: React.FC<MotionProps> = ({
  in: entering = true,
  effect = DEFAULT_EFFECT,
  duration,
  delay,
  easing,
  preset,
  timing,
  intent,
  onAnimationEnd,
  className,
  children,
}) => {
  const effects = typeof effect === 'string' ? [...EFFECT_PRESETS[effect]] : effect;
  const effectKey = typeof effect === 'string' ? effect : JSON.stringify(effect);
  const config = resolveConfig({ duration, delay, easing, preset, timing, intent });

  // Detect if effects contain a CollapseEffect
  const collapseEffect = effects.find(e => e.type === 'collapse') as
    | (MotionEffect & { type: 'collapse'; collapsedHeight?: number })
    | undefined;
  const hasCollapse = collapseEffect !== undefined;
  const collapsedHeight = collapseEffect?.collapsedHeight ?? 0;

  // Track first render to skip initial animation (Requirement 20.4)
  const isFirstRenderRef = useRef(true);

  // Track measured content height for Collapse
  const [contentHeight, setContentHeight] = useState(0);

  const effectStyles = resolveEffectStyles(effects, entering, hasCollapse ? contentHeight : undefined);

  const [currentStyles, setCurrentStyles] = useState<Record<string, string>>(() => {
    if (hasCollapse && isFirstRenderRef.current) {
      // First render: set initial state without animation (Req 20.1, 20.2)
      const baseStyles = entering ? effectStyles.to : effectStyles.from;
      if (entering) {
        // expanded=true: max-height=none to allow free content growth
        return { ...baseStyles, 'max-height': 'none' };
      } else {
        // expanded=false: max-height=collapsedHeight directly
        return { ...baseStyles, 'max-height': collapsedHeight + 'px' };
      }
    }
    return entering ? effectStyles.from : effectStyles.to;
  });

  const divRef = useRef<HTMLDivElement>(null);
  const callbackFiredRef = useRef(false);
  const safetyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const onAnimationEndRef = useRef(onAnimationEnd);

  // Track whether we're in expanded state (max-height is "none")
  const isExpandedRef = useRef(entering && hasCollapse);

  useEffect(() => {
    onAnimationEndRef.current = onAnimationEnd;
  });

  // Measure content height via scrollHeight and observe changes with ResizeObserver (Req 11.1, 11.5, 11.6)
  useEffect(() => {
    if (!hasCollapse) return;

    const el = divRef.current;
    if (!el) return;

    // Initial measurement
    setContentHeight(el.scrollHeight);

    // Observe content size changes
    const observer = new ResizeObserver(() => {
      setContentHeight(el.scrollHeight);
    });
    observer.observe(el);

    return () => {
      observer.disconnect();
    };
  }, [hasCollapse]);

  // Handle expand/collapse animation completion for Collapse effect
  const handleCollapseTransitionEnd = useCallback(() => {
    if (!hasCollapse || !divRef.current) return;

    if (entering) {
      // Expand animation completed: set max-height to "none" (Req 11.3)
      isExpandedRef.current = true;
      setCurrentStyles(prev => ({ ...prev, 'max-height': 'none' }));
    } else {
      isExpandedRef.current = false;
    }
  }, [hasCollapse, entering]);

  // Main animation effect
  useEffect(() => {
    callbackFiredRef.current = false;

    const resolved = resolveConfig({ duration, delay, easing, preset, timing, intent });
    const resolvedEffects = typeof effect === 'string' ? [...EFFECT_PRESETS[effect]] : effect;
    const resolvedHasCollapse = resolvedEffects.some(e => e.type === 'collapse');
    const resolvedCollapseEffect = resolvedEffects.find(e => e.type === 'collapse') as
      | (MotionEffect & { type: 'collapse'; collapsedHeight?: number })
      | undefined;
    const resolvedCollapsedHeight = resolvedCollapseEffect?.collapsedHeight ?? 0;

    const styles = resolveEffectStyles(
      resolvedEffects,
      entering,
      resolvedHasCollapse ? contentHeight : undefined,
    );
    const target = entering ? styles.to : styles.from;

    // Skip animation on first render for Collapse (Req 20.4)
    if (isFirstRenderRef.current) {
      isFirstRenderRef.current = false;

      if (resolvedHasCollapse) {
        if (entering) {
          // expanded=true on mount: show fully expanded, no animation
          isExpandedRef.current = true;
          setCurrentStyles({ ...styles.to, 'max-height': 'none' });
        } else {
          // expanded=false on mount: show collapsed, no animation
          isExpandedRef.current = false;
          setCurrentStyles({ ...styles.from, 'max-height': resolvedCollapsedHeight + 'px' });
        }
        // Still fire callback for first render
        if (onAnimationEndRef.current) {
          onAnimationEndRef.current();
        }
        return;
      }
    }

    if (resolved.reducedMotion && resolved.duration === 0) {
      if (resolvedHasCollapse) {
        if (entering) {
          setCurrentStyles({ ...target, 'max-height': 'none' });
          isExpandedRef.current = true;
        } else {
          setCurrentStyles({ ...target, 'max-height': resolvedCollapsedHeight + 'px' });
          isExpandedRef.current = false;
        }
      } else {
        setCurrentStyles(target);
      }
      if (onAnimationEndRef.current && !callbackFiredRef.current) {
        callbackFiredRef.current = true;
        onAnimationEndRef.current();
      }
      return;
    }

    // For Collapse: handle the "none" → scrollHeight snap before collapsing (Req 11.4)
    if (resolvedHasCollapse && !entering && isExpandedRef.current) {
      // Snap max-height from "none" to current scrollHeight before transitioning
      const el = divRef.current;
      const currentScrollHeight = el ? el.scrollHeight : contentHeight;
      const snapStyles = { ...styles.to, 'max-height': currentScrollHeight + 'px', overflow: 'hidden' };
      setCurrentStyles(snapStyles);
      isExpandedRef.current = false;

      // Use rAF to ensure the snap is painted, then transition to collapsedHeight
      const rafId = requestAnimationFrame(() => {
        setCurrentStyles({ ...target });
      });

      const fireCallback = () => {
        if (onAnimationEndRef.current && !callbackFiredRef.current) {
          callbackFiredRef.current = true;
          handleCollapseTransitionEnd();
          onAnimationEndRef.current();
        }
      };

      const handleTransitionEnd = (e: TransitionEvent) => {
        if (styles.transitionProperties.includes(e.propertyName)) {
          fireCallback();
        }
      };

      if (el) {
        el.addEventListener('transitionend', handleTransitionEnd);
      }

      safetyTimerRef.current = setTimeout(() => {
        fireCallback();
      }, resolved.duration + resolved.delay + 50);

      return () => {
        cancelAnimationFrame(rafId);
        if (el) {
          el.removeEventListener('transitionend', handleTransitionEnd);
        }
        if (safetyTimerRef.current !== null) {
          clearTimeout(safetyTimerRef.current);
          safetyTimerRef.current = null;
        }
      };
    }

    // Standard animation path (also handles Collapse expand)
    setCurrentStyles(entering ? styles.from : styles.to);

    const rafId = requestAnimationFrame(() => {
      setCurrentStyles(target);
    });

    const fireCallback = () => {
      if (onAnimationEndRef.current && !callbackFiredRef.current) {
        callbackFiredRef.current = true;
        if (resolvedHasCollapse) {
          handleCollapseTransitionEnd();
        }
        onAnimationEndRef.current();
      }
    };

    const el = divRef.current;
    const handleTransitionEnd = (e: TransitionEvent) => {
      if (styles.transitionProperties.includes(e.propertyName)) {
        fireCallback();
      }
    };

    if (el) {
      el.addEventListener('transitionend', handleTransitionEnd);
    }

    safetyTimerRef.current = setTimeout(() => {
      fireCallback();
    }, resolved.duration + resolved.delay + 50);

    return () => {
      cancelAnimationFrame(rafId);
      if (el) {
        el.removeEventListener('transitionend', handleTransitionEnd);
      }
      if (safetyTimerRef.current !== null) {
        clearTimeout(safetyTimerRef.current);
        safetyTimerRef.current = null;
      }
    };
  }, [entering, effectKey, duration, delay, easing, preset, timing, intent, contentHeight, handleCollapseTransitionEnd]);

  const transitionValue = (() => {
    // First render with collapse: no transition
    if (hasCollapse && isFirstRenderRef.current) {
      return 'none';
    }
    if (config.reducedMotion && config.duration === 0) {
      return 'none';
    }
    return effectStyles.transitionProperties
      .map((prop) => `${prop} ${config.duration}ms ${config.easing} ${config.delay}ms`)
      .join(', ');
  })();

  const style: CSSProperties = {
    ...currentStyles,
    transition: transitionValue,
  } as CSSProperties;

  return (
    <div ref={divRef} className={className} style={style}>
      {children}
    </div>
  );
};
